apiVersion: v1
kind: Service
metadata:
  name: fulfillorderack-service
  labels:
   app: fulfillorderack
spec:
  selector:
    app: fulfillorderack
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP